### ISSUE TITLE
Update to Django>=3.1.6

### ISSUE THREAD

**Issue by jaynewey** [jaynewey/django-octicons-v10#13]
This project is stuck on Django 2. It needs some work to be updated to 3, for security and compatibility reasons.

I don't have time to do this currently, unfortunately.

**Comment by dylanjw** [comment]
What are some of the security and compatibility issues? Tests are passing with django 3.2.5

**Comment by jaynewey** [comment]
I'll be honest, the tests could do with some work; they only test the core functionality of the package but not the compatibility with Django. Therefore, the tests will pass with any Django version. (I do want to get around to fixing that though)

Before when trying to use the package with Django>=3 I was receiving errors about template tags. However I just made a new test project with Django 3.2.5 and it seems to work!

The security issues are to do with Django<3.1.12 I believe so not really to do with the package itself.

Send a PR with the bumped version and I'll update and release :)
